In [10]:
from utilities import genKSignals, createDataset
from mlClassifier import MaxiumLikelihood
import modulation
import numpy as np

In [11]:
burstSize = 1024
sampleSize = 10
lowestSnr, highestSnr = (10, 11)
snrRange = np.arange(lowestSnr, highestSnr, 1)

In [12]:
X_all = createDataset(modulation.supportedModulation, burstSize, sampleSize, snrRange)

In [13]:
MLClassifier = MaxiumLikelihood(lowestSnr, modulation.supportedModulation)
MLClassifier.fit(None, None)

In [14]:
X = X_all[lowestSnr]

In [15]:
for k, modType in enumerate(modulation.supportedModulation):
    start = k*sampleSize
    end = start+10
    y_predict = MLClassifier.predict(X[start:end])
    print(modType)
    print(y_predict)

2pam
[0 0 0 0 0 0 0 0 0 0]
4pam
[1 1 1 1 1 1 1 1 1 1]
8pam
[2 2 2 2 2 2 2 2 2 2]
2psk
[3 3 3 3 3 3 3 3 3 3]
4psk
[4 4 4 4 4 4 4 4 4 4]
8psk
[5 5 5 5 5 5 5 5 5 5]
4qam
[6 6 6 6 6 6 6 6 6 6]
16qam
[7 7 7 7 7 7 7 7 7 7]
64qam
[8 8 8 8 8 8 8 8 8 8]
256qam
[8 8 8 8 8 8 8 8 8 8]
